name: draftea_pokemon_challenge
description: Tu app de salud.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  


  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: 6.0.4
  custom_refresh_indicator: ^4.0.1
  dartz: 
  dio: ^5.4.0
  event_bus: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  get_it:
  go_router: 12.1.3
  injectable:
  intl:
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  meta:
  package_info_plus: ^8.0.0
  path_provider: ^2.0.12
  pretty_dio_logger: ^1.3.1
  retrofit:
  shared_preferences: ^2.2.2
  shimmer:
  top_snackbar_flutter: ^3.1.0
  universal_platform: ^1.1.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.4.2

dev_dependencies:
  bloc_test:
  build_runner: 2.7.0
  firebase_auth_platform_interface:
  firebase_core_platform_interface:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  injectable_generator:
  json_serializable:
  plugin_platform_interface:
  retrofit_generator:
  very_good_analysis: ^5.1.0

# dependency_overrides:
#   flutter_gen_runner : 5.11.0

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
    rive: false
  assets:
    outputs:
      package_parameter_enabled: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo_android.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo_android.jpg"
  web:
    generate: false
    image_path: "assets/images/draftea_pokemon_challenge_new_logo_black.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: false
    image_path: "assets/images/draftea_pokemon_challenge_new_logo_black.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/images/draftea_pokemon_challenge_new_logo_black.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/metropolis/Metropolis-Black.otf
        - asset: fonts/metropolis/Metropolis-BlackItalic.otf
        - asset: fonts/metropolis/Metropolis-Bold.otf
        - asset: fonts/metropolis/Metropolis-BoldItalic.otf
        - asset: fonts/metropolis/Metropolis-ExtraBold.otf
        - asset: fonts/metropolis/Metropolis-ExtraBoldItalic.otf
        - asset: fonts/metropolis/Metropolis-ExtraLight.otf
        - asset: fonts/metropolis/Metropolis-ExtraLightItalic.otf
        - asset: fonts/metropolis/Metropolis-Light.otf
        - asset: fonts/metropolis/Metropolis-LightItalic.otf
        - asset: fonts/metropolis/Metropolis-Medium.otf
        - asset: fonts/metropolis/Metropolis-MediumItalic.otf
        - asset: fonts/metropolis/Metropolis-Regular.otf
        - asset: fonts/metropolis/Metropolis-RegularItalic.otf
        - asset: fonts/metropolis/Metropolis-SemiBold.otf
        - asset: fonts/metropolis/Metropolis-SemiBoldItalic.otf
        - asset: fonts/metropolis/Metropolis-Thin.otf
        - asset: fonts/metropolis/Metropolis-ThinItalic.otf
    - family: Volkhov    
      fonts:
        - asset: fonts/volkhov/Volkhov-Regular.ttf
        - asset: fonts/volkhov/Volkhov-Italic.ttf
        - asset: fonts/volkhov/Volkhov-Bold.ttf
        - asset: fonts/volkhov/Volkhov-BoldItalic.ttf
      
